version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./src:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: mysql:5.7
    env_file:
      - ./environments/env
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
