apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rails-ing
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: rails
          servicePort: 3000
